ExternalProject_Add(flatbuffers
    SOURCE_DIR "${PROJECT_SOURCE_DIR}/extern/flatbuffers"
    INSTALL_DIR "${Battleship_INSTALL_PREFIX}"
    CMAKE_ARGS
        -DBUILD_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS}
        -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
        -DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
)
